### PR TITLE
feat: Add new template files

### LINKED ISSUE #27: Add new document templates to example-files
- [ ] Collect full list of files with @jancborchardt 
- [ ] Ensure that fonts look proper with a default Collabora setup
- [ ] Check back with collabora about making them language agnostic
- [ ] pull request

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] Adapt fonts that look weird in previews
- [x] Double check font usages
- [x] Double check gotong-royong naming with @jancborchardt

### CODE REVIEW

**Comment by juliusknorr** [comment]
Screenshot 2023-05-11 at 17 50 04
Screenshot 2023-05-11 at 17 50 31
Screenshot 2023-05-11 at 17 50 48
Screenshot 2023-05-11 at 17 50 55

**Review by nimishavijay — CHANGES_REQUESTED** [review]
The designs look great! However, there is an issue while opening the files because of incompatible extensions. All the extensions should either be `.odt`, `.ods`, or `.odp`. There are some files which have different extensions like `.ott`, `.ots` and `.otp` and so I can't open these files on NC or anywhere else.

**Comment by juliusknorr** [comment]
> There are some files which have different extensions like .ott, .ots and .otp and so I can't open these files on NC or anywhere else.

Those are template files that libreoffice/collabora can use to create new files from, opening indeed is not working with Collabora just by clicking on the file but LibreOffice on the desktop should work fine. Nevertheless maybe we should rather keep them as regular files for now as this also allows users then to make changes to the templates within Nextcloud.

**Comment by juliusknorr** [comment]
@nimishavijay Updated them with the above reasoning, can you check again? :)

**Comment by juliusknorr** [comment]
@jancborchardt Since we discussed sorting currently they seem to be in order they have been added to the users template directory, so by default this should be sorted by name as we as we copy them over during template folder creation time at once. On my set they were just mixed because I was putting them in place in random order.

**Review by nimishavijay — APPROVED** [review]
Works now! :) 🚀

**Comment by jancborchardt** [comment]
@juliushaertl ah ok, so they will be sorted alphabetically starting with A?

In that case can you do some renaming so the sorting is nicer:
- Minimalist resume → Resume
- Basic syllabus → Syllabus
- I'd also like for "Business model canvas" to be sorted later … maybe "The business model canvas" as it's a thing?

Otherwise good to go @juliushaertl!

**Review by jancborchardt — APPROVED** [review]
Nice! :)

**Pull request merged**
