### PR TITLE
Fix accessibility issues in PDF

### PR DESCRIPTION
**Pull request by cartierbresson**
An updated version of Reasons to use Nextcloud (Fixed accessibility issues in PDF).

### CODE REVIEW

**Comment by jancborchardt** [comment]
Thanks @cartierbresson :)

(For the record, DCO can be ignored here I assume cause it’s Marija? @karlitschek )

**Comment by jancborchardt** [comment]
@cartierbresson  2 questions about it :)
- The document doesn’t seem to have an outline, shouldn’t it? (Like having the headings of "Executive summary", "Nextcloud Talk", and so on. Also came up checking with http://checkers.eiii.eu/en/pdfcheck/ where it says the document does not have any bookmarks.
- The "accreport.html" is attached – is that how it’s done? It seems a bit weird

**Review by vaneslie — COMMENTED** [review]
Looks good to me. The only error I found is the "experimental" one about headers and footers so I think we can ignore that.

**Comment by karlitschek** [comment]
> Thanks @cartierbresson :)
> 
> (For the record, DCO can be ignored here I assume cause it’s Marija? @karlitschek )

Yes. She did it.

**Review by vaneslie — COMMENTED** [review]
Can't see anything wrong 😊  Adobe recommended to check the colour contrast and tags but to me it looks good. No real issues. Go 🏁 😆

**Pull request closed without merging**
