### PR TITLE
Add remaining templates

### PR DESCRIPTION
**Pull request by jancborchardt**
Follow-up to https://github.com/nextcloud/example-files/pull/12

For easier reviewing, attached PDF/image previews for all the different templates:

## Nextcloud Text
(Easier to see in the code / changeset)
- Meeting notes
- Project plan
- Readme.md template

## Documents
[Letter.pdf](https://github.com/nextcloud/example-files/files/5934319/Letter.pdf)
[Invoice.pdf](https://github.com/nextcloud/example-files/files/5935025/Invoice.pdf)

## Spreadsheets
[Diagram & table.pdf](https://github.com/nextcloud/example-files/files/5934321/Diagram.table.pdf)
[Expense report.pdf](https://github.com/nextcloud/example-files/files/5935026/Expense.report.pdf)

## Presentations
[Simple.pdf](https://github.com/nextcloud/example-files/files/5938966/Simple.pdf)
[Elegant.pdf](https://github.com/nextcloud/example-files/files/5934318/Elegant.pdf)

## Whiteboards
**SWOT analysis**
SWOT analysis new

**Impact effort matrix**
Impact effort matrix

### CODE REVIEW

**Review by stefan-niedermann — APPROVED** [review]

**Comment by jancborchardt** [comment]
Went through some revisions thanks to @juliushaertl @vaneslie @ogasser @stefan-niedermann @nimisha-vijay, now fully good to go! :)

**Comment by jancborchardt** [comment]
@rullzer @juliushaertl this is mergable, just waiting for second review.

**Review by julien-nc — APPROVED** [review]
Beautiful!
The `.whiteboard` files are valid and load fine in spacedeck.

**Review by juliusknorr — APPROVED** [review]

**Comment by juliusknorr** [comment]
Ah merged faster than the backport bot :grin:

**Pull request merged**
