### PR TITLE
Add new diagram templates

### PR DESCRIPTION
**Pull request by juliusknorr**
Implements https://github.com/nextcloud/example-files/issues/21 

by adding the previously discussed template files to our shipped templates

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looking good! :)

**Comment by jancborchardt** [comment]
@eneiluj @nimishavijay @marcoambrosini could someone review this, and can we also backport this?

**Review by nimishavijay — APPROVED** [review]

**Pull request merged**
