### PR TITLE
changed example odt to docx, minor content changes

### LINKED ISSUE #7: Use docx/xlsx/pptx for office files
Onlyoffice breaks the currently shipped odt file. 
Since Onlyoffice is virtually shipped with 18+, we should make sure the example files are properly handled.

### PR DESCRIPTION
**Pull request by wiswedel**
implements https://github.com/nextcloud/example-files/issues/7

Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>

### CODE REVIEW

**Comment by wiswedel** [comment]
#### before
before

#### after
after

**Comment by skjnldsv** [comment]
I find it kind of sad to go for non open-sourced file format :(

**Comment by jancborchardt** [comment]
The changes to `Example.md` are of course great.

For the odt/docx I would say though that this should be fixed at OnlyOffice, and that we shouldn’t change to docx for this. We already get some criticism for partnering with a project which is perceived as not-so-open-source by some, so we shouldn’t make it worse by putting docx over odt in the default files.

Or what do you think @jospoortvliet @karlitschek?

**Comment by karlitschek** [comment]
Nice. A new contributor :-)
I´m not religious about the file format. Both are widely used and are supported by Nextcloud. Of course docx has better compatibility as discussed. Not only ONLYOFFICE but also the applications that normal users have on their phones and desktops. So I think switching to docx is ok.

**Review by MorrisJobke — APPROVED** [review]

**Pull request merged**
